### ISSUE TITLE
Downloading the cold starts profiles

### ISSUE THREAD

**Issue by eldiegod** [remorses/debug-next-cold-starts#1]
Tried on my project and was able to get some downloads of `?vercel-profile-cpu`, tho could only get `?vercel-profile-require` on one page that had only a redirect and some pages would throw a 500.

but after a bit of testing noticed that couldn't get any download anymore even for `?vercel-profile-cpu` also tried your site example but also the same happened.

Tested on safari and arc

Update: I was able to get `?vercel-profile-require` now after a redeploy for api routes.
Tho now I'm struggling a bit interpreting the data and figuring out what part of it is the cold starts for example:
![image](https://github.com/remorses/profile-next-cold-starts/assets/10615263/3b6b1038-d9d0-45c3-90ec-59c4ac88bf1b)

**Comment by remorses** [comment]
It’s easier to interpret the result by pasting both, ideally you would run the cpu profile first and then require, the require shouldn’t change much even if it’s a hot start because I am deleting the require cache

the whole graph is a cold start, some parts are empty because that graph only contain the require times

I will soon make a blog post with tips for optimizing cold starts

**Comment by remorses** [comment]
If a page throws a 500 can you paste the Vercel logs here? it may be a bug in this code

**Comment by remorses** [comment]
One way to optimize your cold starts would be to not import `_app`, you are somehow importing it even in your API handlers

**Comment by bogdansalau** [comment]
Any download returns 500 with this error.

```
Unhandled Rejection: TypeError: Cannot redefine property: __import_unsupported
    at Function.defineProperty (<anonymous>)
    at enhanceGlobals (/var/task/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/globals.js:101:12)
    at Object.<anonymous> (/var/task/node_modules/.pnpm/next@15.0.3_@babel+core@7.26.0_@opentelemetry+api@1.9.0_react-dom@18.3.1_react@18.3.1__react@18.3.1/node_modules/next/dist/server/web/globals.js:109:1)
    at Module.<anonymous> (/opt/rust/bytecode.js:1:1435)
    at A.l._compile (/opt/rust/bytecode.js:1:3150)
    at <unknown> (/opt/rust/nodejs.js:1:12124)
    at Function.Rr (/opt/rust/nodejs.js:1:12498)
Node.js process exited with exit status: 128. The logs above can help with debugging the issue.
```
